[transfer]
method = "data"  # Faster and more secure than "name"

[validation]
method = "individual"
algorithm = "SHA256"
vanillaKickMessage = "Anti-cheat: missing required mods.\nGet the correct modpack from the server website."
deniedKickMessage = "Anti-cheat: illegal mods detected.\nPlease remove cheats before joining."

[validation.individual]
blacklist = ["meteor-client", "wurst", "aristois", "future", "impact", "salhack", "lambda", "kami", "zerohack"]
whitelist = []

[validation.group]
hash = []
softWhitelist = []

[motd]
showInstalled = false  # ← Turning this off speeds up login
blacklist = ["Meteor", "Wurst", "Aristois"]
whitelist = []
hash = []  # ← Remove static MOTD hashing; not needed

[debug]
debug = false
version = 8
